version: '3.4'

services:
  atriskhistory.api:
    image: atriskhistoryapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AtRiskHistory.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_atriskhistory.api$
    volumes:
      - C:\proj\admin\GitRepos\Projects\AtRiskModernization\src\Microservices\AtRiskHistory\AtRiskHistory.API:/app
      - C:\Users\SMishra24\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_atriskhistory.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_atriskhistory.api$ \"bin/Debug/netcoreapp2.2/AtRiskHistory.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
